export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";

export const SET_THEME = "SET_THEME";
export const OPEN_SLIDER_DISKTOP = "OPEN_SLIDER_DISKTOP";
export const CLOSE_SLIDER_DISKTOP = "CLOSE_SLIDER_DISKTOP";

export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
